title: Adam Muzaffar Abd Razak
description: Engineering Student specializing in digital systems, FPGA design, and electronics. Strong foundation in circuit analysis, hardware description languages, and simulation tools. Passionate about building efficient and reliable hardware systems.
theme: jekyll-theme-minimal
